### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by adilbonzi** [SaranshKejriwal/kinect_nav#1]
Hi, Saransh. Thank you for the repository for obstacle avoidance. Im trying to work with Kinect One, using ros indigo. So, im implementing obstacle avoidance in my project. I used git clone for the repository into my home folder. And when i run the command sudo mark3.py, it gives me the error, command not found. Can you guide me on this matter? Like, can explain the procedure, on how to do execution.

**Comment by SaranshKejriwal** [comment]
Here's the set of commands I followed:

https://drive.google.com/file/d/0B7aF0st7oTiBQTBRMTM2b2xMLWM/view?usp=drivesdk

I hope this helps..

**Comment by adilbonzi** [comment]
Thank you saranash, this helped alot. But I have tested both kinects. Kinect for Xbox 360 and Kinect for Xbox One. Freenect library only runs with Kinect for Xbox360. It does not detect Kinect for Xbox One. It gave me the disparity image and live video. 
But when i compiled the main.py file, and ran it through a separate command window, it gave me this error,"

File "main.py", line 21
SyntaxError: Non-ASCII character '\xe2' in file main.py on line 21, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
 "

**Comment by will-conrad** [comment]
I got this error too! How do I fix this.  I’ve looked through the code in the main file but can’t find \xe2.
